name: transformer-circuits

dependencies:
  - python=3.11
  - pip
  - pip:
    - torch==2.0.1
    - ipython
    - einops
    - numpy
    - matplotlib
    - circuitsvis
    - plotly==5.15.0
    - fancy-einsum
    - jaxtyping
    - transformers
    - datasets
    - dataclasses
    - git+https://github.com/neelnanda-io/TransformerLens